### ISSUE TITLE
Support `aws-lc-rs`

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket-sdk#192]
**Issue or Feature Request:**
In order to provide fips support, Rust packages typically lean on [`aws-lc`](https://github.com/aws/aws-lc) for crypto. rustls leans on [`aws-lc-rs`](https://github.com/aws/aws-lc-rs) for bindings.

Bindings aren't shipped upstream for Bottlerocket's build targets (`$ARCH-bottlerocket-linux-musl`) so the build process tries to use rust-bindgen to create them, which fails because we don't ship that in the SDK.

I think it would be ideal if the SDK shipped it's own system `aws-lc` and bindings that we could depend on during Brupop's build.

**Comment by arnaldo2792** [comment]
In https://github.com/bottlerocket-os/bottlerocket-sdk/pull/209, we added the machinery required to compile `aws-lc-rs` from source. Instead of providing `aws-lc-rs` bindings, we should just let Brupop compile `aws-lc-rs` like we do in the Bottlerocket Core kit. Closing this issue since Brupop should be able to migrate to `aws-lc-rs` once it uses newer versions of the Bottlerocket SDK (there is an issue (https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/703) to track that work in the Brupop repository).
