### ISSUE TITLE
glibc needs to be the same version across the Fedora base image, the SDK, and the OS

### ISSUE THREAD

**Issue by iliana** [bottlerocket-os/bottlerocket-sdk#31]
Some of our build scripts are built with the Bottlerocket toolchain, but run with the Fedora glibc version in the SDK image. If we try to upgrade glibc in the OS ahead of the SDK, we get symbol version mismatches; if we try to upgrade glibc in the SDK ahead of the Fedora base image, we get symbol version mismatches.

This issue is to track unwinding the dependency of things built with the Bottlerocket toolchain on the particulars of the Fedora glibc.

**Comment by bcressey** [comment]
We omit the build of glibc here from the final SDK, but I expect we'll ultimately need to fix it here.

One thing that might work is to define our own custom Rust targets that are copies of the "unknown" ones; part of the trouble is the "host == target" confusion that happens with the x86_64-unknown-linux-gnu triple.

That could double as a fix to #28 since the major reason why that's "hard" is that we have the same underlying confusion.

**Comment by iliana** [comment]
> We omit the build of glibc here from the final SDK, but I expect we'll ultimately need to fix it here.

We do, but various parts of rustlib depend on the toolchain glibc. I ran across compilation errors when building the OS after bumping glibc here.
